Update prerm postrm and postinst files

diff --git a/debian/sddm.postrm b/debian/sddm.postrm
--- a/debian/sddm.postrm
+++ b/debian/sddm.postrm
@@ -1,41 +1,34 @@
 #!/bin/sh
 set -e
 
-if [ "$1" = "purge" ] ; then
-        rm -f /etc/sddm.conf
+case "$1" in
+    purge)
+        update-rc.d sddm remove > /dev/null
 
-        if [ -d /var/log/sddm ]; then
-                rm -r /var/log/sddm
-        fi
-
-        if [ -d /var/cache/sddm ]; then
-                rm -r /var/cache/sddm
-        fi
-
-        if [ -d /var/run/sddm/authority ]; then
-                rm -r /var/run/sddm/authority
-        fi
+        if [ -d /var/cache/sddm ]; then rm -r /var/cache/sddm; fi
+        if [ -d /var/lib/sddm ]; then rm -r /var/lib/sddm; fi
+        if [ -d /var/log/sddm ]; then rm -r /var/log/sddm; fi
+        if [ -d /var/run/sddm ]; then rm -r /var/run/sddm/authority; fi
 
         if getent passwd sddm >/dev/null; then
-                if [ -x /usr/sbin/deluser ]; then
-                        deluser --system sddm
-                fi
+            if [ -x /usr/sbin/deluser ]; then
+                deluser --system sddm || echo "Could not remove sddm user."
+            fi
         fi
-
         if getent group sddm >/dev/null; then
-                if [ -x /usr/sbin/delgroup ]; then
-                        delgroup --system sddm
-                fi
+            if [ -x /usr/sbin/delgroup ]; then
+                delgroup --system sddm || echo "Could not remove sddm group."
+            fi
         fi
-
-        # we cannot use the --remove-home option when we delete the user above
-        # because it will refuse to remove things in /var, so clean it up this
-        # way
-        if [ -d /var/lib/sddm ]; then
-                rm -r /var/lib/sddm
+        ;;
+    abort-install|abort-upgrade)
+        # roll back displacement of default display manager file
+        if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" ]; then
+            # FIXME - redo this part uses shell-lib.sh from xfree86
+            #observe "rolling back change of default X display manager"
+            mv "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" "$DEFAULT_DISPLAY_MANAGER_FILE"
         fi
-
-        update-rc.d sddm remove > /dev/null
-fi
+        ;;
+esac
 #DEBHELPER#
 exit 0
